const affirmations = [
  'You got this',
  "You'll figure it out",
  "You're a smart cookie",
  'I believe in you',
  'Sucking at something is the first step towards being good at something',
  'Struggling is part of learning',
  "Everything has cracks - that's how the light gets in",
  "Mistakes don't make you less capable",
  'We are all works in progress',
  'You are a capable human',
  'You know more than you think',
  '10x engineers are a myth',
  "If everything was easy you'd be bored",
  'I admire you for taking this on',
  "You're resourceful and clever",
  "You'll find a way",
  "I know you'll sort it out",
  "Struggling means you're learning",
  "You're doing a great job",
  "It'll feel magical when it's working",
  "I'm rooting for you",
  'Your mind is full of brilliant ideas',
  'You make a difference in the world by simply existing in it',
  'You are learning valuable lessons from yourself every day',
  'You are worthy and deserving of respect',
  'You know more than you knew yesterday',
  "You're an inspiration",
  'Happiness is not out there, it’s in you',
  'Giving a helping hand brings happiness',
  'Your succes and happiness lies within you',
  "The harder you strive for something, the greater you'll feel when you achieve it",
  'Set goals and celebrate them , no matter how small',
];

const getRandomAffirmation = () =>
  affirmations[Math.floor(Math.random() * affirmations.length)];
module.exports = getRandomAffirmation;
