const affirmations = [
  "You got this",
  "You'll figure it out",
  "You're a smart cookie",
  "I believe in you",
  "Sucking at something is the first step towards being good at something",
  "Struggling is part of learning",
  "Everything has cracks - that's how the light gets in",
  "Mistakes don't make you less capable",
  "We are all works in progress",
  "You are a capable human",
  "You know more than you think",
  "10x engineers are a myth",
  "If everything was easy you'd be bored",
  "I admire you for taking this on",
  "You're resourceful and clever",
  "You'll find a way",
  "I know you'll sort it out",
  "Struggling means you're learning",
  "You're doing a great job",
  "It'll feel magical when it's working",
  "I'm rooting for you",
  "Your mind is full of brilliant ideas",
  "You make a difference in the world by simply existing in it",
  "You are learning valuable lessons from yourself every day",
  "You are worthy and deserving of respect",
  "You know more than you knew yesterday",
  "You're an inspiration",
  "Your life is already a miracle of chance waiting for you to shape its destiny",
  "Your life is about to be incredible",
  "Nothing is impossible. The word itself says 'I’m possible!'",
  "Failure is just another way to learn how to do something right",
  "I give myself permission to do what is right for me",
  "You can do it",
  "It is not a sprint, it is a marathon. One step at a time",
  "Success is the progressive realization of a worthy goal",
  "People with goals succeed because they know where they’re going",
  "All you need is the plan, the roadmap, and the courage to press on to your destination",
  "The opposite of courage in our society is not cowardice... it is conformity",
  "Whenever we’re afraid, it’s because we don’t know enough. If we understood enough, we would never be afraid",
  "The past does not equal the future",
  "The path to success is to take massive, determined action",
  "It’s what you practice in private that you will be rewarded for in public",
  "Small progress is still progress",
  "Don't worry if you find flaws in your past creations, it's because you've evolved",
  "Starting is the most difficult step - but you can do it",
  "Don't forget to enjoy the journey",
  "It's not a mistake, it's a learning opportunity",
  "Look in the mirror. That's your competition",
  "If you want it, work for it",
  "You are needed, you deserve the best, you are here for a reason",
  "You are not your thoughts, you are the one listening to them",
  "Don't give up on yourself.",
  "Maybe you don't need the whole world to love you. Maybe you just need one person.",
  "Good things come to those who work their asses off and never give up.",
  "Never give up.",
  "It is not the length of life, but the depth.",
  "Action expresses priorities.",
  "Being at ease with not knowing is crucial for answers to come to you.",
  "Continuous improvement is better than delayed perfection.",
  "Dear future, I am ready.",
  "Don't trade your authenticity for approval.",
  "Find peace in what you cannot change.",
  "Good things take time.",
  "I walk slowly but I never walk backward",
  "I'd hug you all day if I could.",
  "It may take time but things will get better.",
  "It's ok to take a break.",
  "Keep going.",
  "Life is a journey, not a destination.",
  "Never regreat trying hard.",
  "No matter what, just keep going.",
  "Replace expectation with gratitude.",
  "The best things come to those who never give up.",
  "Wake up with a purpose",
  "Worry less, smile more.",
  "You have always been enough.",
  "Your only limit is your mind.",
  "Your voice is my favourite sound.",
  "Work on you, for you.",
  "Be better than every previous version of yourself",
  "You will get through this.",
  "Be here now. Be someplace else later",
  "Let's make 2021 our best year ever !"
];

module.exports = affirmations
