const affirmations = [
  "You got this",
  "You'll figure it out",
  "You're a smart cookie",
  "I believe in you",
  "Sucking at something is the first step towards being good at something",
  "Struggling is part of learning",
  "Everything has cracks - that's how the light gets in",
  "Mistakes don't make you less capable",
  "We are all works in progress",
  "You are a capable human",
  "You know more than you think",
  "10x engineers are a myth",
  "If everything was easy you'd be bored",
  "I admire you for taking this on",
  "You're resourceful and clever",
  "You'll find a way",
  "I know you'll sort it out",
  "Struggling means you're learning",
  "You're doing a great job",
  "It'll feel magical when it's working",
  "I'm rooting for you",
  "Your mind is full of brilliant ideas",
  "You make a difference in the world by simply existing in it",
  "You are learning valuable lessons from yourself every day",
  "You are worthy and deserving of respect",
  "You know more than you knew yesterday",
  "You're an inspiration",
  "Yes, I have passed the literature lesson!" ,
  "Is it true that we will spend your birthday at sea?",
  "Are you sure you can with everything?",
  "Have you really believed that I would not see you again?",
  "Are you sure you are ready for the competition?",
  "I have rightly come to see you",
  "Certainly he tripped over that lamp",
  "Certainly this book is the most interesting of all that you have",
  "I will certainly go to visit you"
];

const getRandomAffirmation = () => affirmations[Math.floor(Math.random() * affirmations.length)];
module.exports = getRandomAffirmation;
